### ISSUE TITLE
PDF forms structure is lost while read

### ISSUE THREAD

**Issue by abhilash-threadstarttech** [microsoft/markitdown#195]
Hello,

While trying to read pdf forms, the text content output does not preserve the structure of the form. For example like below 

The form I tried is [eerf_form_3.pdf](https://github.com/user-attachments/files/18219856/eerf_form_3.pdf)

But this is not extracting any of the label values, just prints out Test Name and Test address when tested with the following code

```
markdown = MarkItDown()
result = markdown.convert("eerf_form_3.pdf")
file = open("eerf_form_3.md", "w", encoding="utf-8")
file.write(result.text_content)
file.close() 
```

Not sure whether I am doing something wrong or any options are available for customizing this behavior

**Comment by gagb** [comment]
Related to #131; Lets continue discussion there.
