### ISSUE TITLE
Removing if condition at line 1074

### ISSUE THREAD

**Issue by Viddesh1** [microsoft/markitdown#65]
https://github.com/microsoft/markitdown/blob/81e3f24acd0049a59cd2dcb2d01d0a98cc57c734/src/markitdown/_markitdown.py#L1066-L1075

```python
    def _append_ext(self, extensions, ext):
        """Append a unique non-None, non-empty extension to a list of extensions."""
        if ext is None:
            return
        ext = ext.strip()
        if ext == "":
            return
       
        extensions.append(ext)

``` 
Hello,  I am new to this project. Thanks for creating it.

Rather that if condition at line number 1074 we can directly added the ext to extensions.

**Comment by afourney** [comment]
Hah, good catch. Looks like line 1074 is some debug code. I will review the PR, asap.
