### ISSUE TITLE
microsoft excel document locked how to find source

### ISSUE THREAD

**Issue by snake-plant-care-indoors** [microsoft/markitdown#66]
Here are the **10 steps** to identify the source of a locked Excel file:

1. **Check for Password Protection**: Open the file to see if it requests a password.  
2. **Check for Read-Only Mode**: Right-click → Properties → Uncheck "Read-only".  
3. **Check File Ownership**: Look for a message showing who has the file open.  
4. **Review Recent Changes**: View version history (OneDrive/SharePoint).  
5. **Check Hidden Excel Processes**: Close all Excel processes in Task Manager.  
6. **Check Shared Network Access**: Confirm if anyone on the network has the file open.  
7. **Save a Copy of the File**: Save the file with a new name or location.  
8. **Check File Properties**: Right-click → Properties → Security tab for ownership.  
9. **Use Excel Safe Mode**: Press `Ctrl + Excel` to open Excel in Safe Mode.  
10. **Consult IT Admin**: Request admin tools to identify active locks on the file.

**Comment by afourney** [comment]
I've not done testing with locked office documents (so I'm not sure exactly what errors might occur), but I would NOT expect them to work with this library.
