### ISSUE TITLE
PDF and JPG do not convert.

### ISSUE THREAD

**Issue by josangmi** [microsoft/markitdown#9]
PDF and JPG  in the future?

**Comment by gagb** [comment]
Pdfs are supported! How would you convert a JPG to markdown?

**Comment by adrianliechti** [comment]
Maybe an OCR pre-process or a llm model doing something similar

Inspiration could be found at similar projects:
https://github.com/DS4SD/docling
https://github.com/Unstructured-IO/unstructured

both seem to accept images

**Comment by gagb** [comment]
Good point. This is related to #12.
