### ISSUE TITLE
Feature request: Add support for pathlib.Path

### ISSUE THREAD

**Issue by l-lumin** [microsoft/markitdown#90]
### Description
`pathlib.Path` is widely used and preferred over `os` for file system operations in modern Python. It would be beneficial to support pathlib.Path 

## Related code
https://github.com/microsoft/markitdown/blob/ad5d4fb1394ad927c0dba86a135fdf9224383123/src/markitdown/_markitdown.py#L1044-L1065

**Comment by SigireddyBalasai** [comment]
@ameyakhot i already did it
