### ISSUE TITLE
TypeError: MarkItDown.__init__() got an unexpected keyword argument 'llm_client'

### ISSUE THREAD

**Issue by gurnamfs** [microsoft/markitdown#99]
md = MarkItDown(llm_client=client, llm_model="gpt-4o")

**Comment by SigireddyBalasai** [comment]
make sure that you are using latest version use git install if possible

**Comment by gagb** [comment]
Sorry for not adding depreciation warning. See #101

**Comment by afourney** [comment]
#101 will at least correct this issue. I'll cut a new release ASAP to address this.

**Comment by afourney** [comment]
Version 0.0.1a3 is out now, with this corrected.
